import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { ModeToggle } from "@/components/mode-toogle";
import { Toaster } from "@/components/ui/sonner";
import Link from "next/link";
import * as React from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// ==========================================
// KROK 1: Zmemoizowany nagłówek
// ==========================================
const HeaderComponent = () => {
  return (
    <header className="border border-b-chart-5 sticky top-0 z-50 w-full border-b bg-background max-w-5xl mx-auto">
      <div className="max-w-5xl mx-auto flex h-16 items-center justify-between px-8">
        <Link
          href="/"
          className="font-bold text-xl tracking-wider hover:opacity-80 transition-opacity"
        >
          e-formularze
        </Link>
        <ModeToggle />
      </div>
    </header>
  );
};

const MemoizedHeader = React.memo(HeaderComponent);

// ==========================================
// KROK 2: Zmemoizowana stopka
// ==========================================
const FooterComponent = () => {
  return (
    <footer>
      <div className="border-t-chart-5 border max-w-5xl mx-auto flex flex-col items-center justify-between gap-4 px-8 py-4 md:flex-row">
        <p className="text-sm text-muted-foreground">
          Potrzebujesz aplikacji dla swojej firmy, zrobię ją dla Ciebie, kliknij w{" "}
          <Link href="" className="font-bold underline">
            link
          </Link>{" "}
          do mojego portfolio.
        </p>
      </div>
    </footer>
  );
};

const MemoizedFooter = React.memo(FooterComponent);

// ==========================================
// KROK 3: Główny Layout aplikacji
// ==========================================
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pl" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} min-h-screen flex flex-col bg-background font-sans antialiased`}
      >
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          
          {/* Zoptymalizowany nagłówek */}
          <MemoizedHeader />

          {/* CONTENT */}
          <main className="sm:border flex-1 flex flex-col container mx-auto max-w-5xl sm:py-6 sm:px-8">
            {children}
          </main>
          
          {/* Zoptymalizowana stopka */}
          <MemoizedFooter />

        </ThemeProvider>
        <Toaster richColors closeButton position="top-center" />
      </body>
    </html>
  );
}